name: Auto Label New Issues

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  label-new-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Label new issue
        uses: actions/github-script@0.9.0
        with:
          script: |
            const issue = context.payload.issue;
            const defaultLabel = "סטטוס: חדש";

            // Extract the selected option label from the issue body
            const body = issue.body;
            const match = body.match(/### Apply labels to this issue\s*\n(.*?)\n/);
            const optionLabel = match ? match[1].trim() : null;

            const allowedOptions = [
              "תפריט: 940",
              "תפריט: 9999"
            ];

            let labelsToAdd = [defaultLabel];

            if (optionLabel && allowedOptions.includes(optionLabel)) {
              labelsToAdd.push(optionLabel);
            } else {
              await github.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `⚠️ נא לבחור תפריט מהרשימה: ${allowedOptions.join(", ")}.`
              });
              return;
            }

            await github.issues.addLabels({
              ...context.repo,
              issue_number: issue.number,
              labels: labelsToAdd
            });
