name: Auto Label New Issues

on:
  issues:
    types:
      - opened

permissions:
  issues: write
  
jobs:
  label-new-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Label new issue
        uses: actions/github-script@0.9.0
        with:
          script: |
            const issue = context.payload.issue;
            const label = "סטטוס: חדש";
            await github.issues.addLabels({
              ...context.repo,
              issue_number: issue.number,
              labels: [label]
            });
