name: Auto Label New Issues

on:
  issues:
    types:
      - opened

permissions:
  issues: write

jobs:
  label-new-issues:
    runs-on: ubuntu-latest

    steps:
      - name: Label new issue
        uses: actions/github-script@0.9.0
        with:
          script: |
            const issue = context.payload.issue;
            const defaultLabel = "סטטוס: חדש";

            const body = issue.body || "";
            const match = body.match(/### Labels\s*\n+([^\n]+)/);
            const optionLabel = match ? match[1].trim() : null;

            const allowedOptions = [
              "תפריט: 940",
              "תפריט: 9999"
            ];

            // Always apply the default label first
            await github.issues.addLabels({
              ...context.repo,
              issue_number: issue.number,
              labels: [defaultLabel]
            });

            // Then check if option label is valid
            if (!optionLabel || !allowedOptions.includes(optionLabel)) {
              await github.issues.createComment({
                issue_number: issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `❌ נא לבחור תפריט מהרשימה: ${allowedOptions.join(", ")}`
              });
              
              return;
            }

            // Add the valid option label
            await github.issues.addLabels({
              ...context.repo,
              issue_number: issue.number,
              labels: [optionLabel]
            });
